// Code generated by MockGen. DO NOT EDIT.
// Source: services/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=services/interfaces.go -destination=services/mock_interfaces.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	auth "github.com/opengittr/ogtr/backend/auth"
	geo "github.com/opengittr/ogtr/backend/geo"
	models "github.com/opengittr/ogtr/backend/models"
	scanner "github.com/opengittr/ogtr/backend/scanner"
	gomock "go.uber.org/mock/gomock"
	gofr "gofr.dev/pkg/gofr"
)

// MockUserStore is a mock of UserStore interface.
type MockUserStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserStoreMockRecorder
	isgomock struct{}
}

// MockUserStoreMockRecorder is the mock recorder for MockUserStore.
type MockUserStoreMockRecorder struct {
	mock *MockUserStore
}

// NewMockUserStore creates a new mock instance.
func NewMockUserStore(ctrl *gomock.Controller) *MockUserStore {
	mock := &MockUserStore{ctrl: ctrl}
	mock.recorder = &MockUserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStore) EXPECT() *MockUserStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserStore) Create(ctx *gofr.Context, name, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserStoreMockRecorder) Create(ctx, name, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserStore)(nil).Create), ctx, name, email)
}

// GetByEmail mocks base method.
func (m *MockUserStore) GetByEmail(ctx *gofr.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserStoreMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserStore)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserStore) GetByID(ctx *gofr.Context, id int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserStoreMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserStore)(nil).GetByID), ctx, id)
}

// MockOrgStore is a mock of OrgStore interface.
type MockOrgStore struct {
	ctrl     *gomock.Controller
	recorder *MockOrgStoreMockRecorder
	isgomock struct{}
}

// MockOrgStoreMockRecorder is the mock recorder for MockOrgStore.
type MockOrgStoreMockRecorder struct {
	mock *MockOrgStore
}

// NewMockOrgStore creates a new mock instance.
func NewMockOrgStore(ctrl *gomock.Controller) *MockOrgStore {
	mock := &MockOrgStore{ctrl: ctrl}
	mock.recorder = &MockOrgStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrgStore) EXPECT() *MockOrgStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrgStore) Create(ctx *gofr.Context, name, slug string, autoJoinDomain *string) (*models.Org, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name, slug, autoJoinDomain)
	ret0, _ := ret[0].(*models.Org)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrgStoreMockRecorder) Create(ctx, name, slug, autoJoinDomain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrgStore)(nil).Create), ctx, name, slug, autoJoinDomain)
}

// GetByAutoJoinDomain mocks base method.
func (m *MockOrgStore) GetByAutoJoinDomain(ctx *gofr.Context, domain string) (*models.Org, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAutoJoinDomain", ctx, domain)
	ret0, _ := ret[0].(*models.Org)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAutoJoinDomain indicates an expected call of GetByAutoJoinDomain.
func (mr *MockOrgStoreMockRecorder) GetByAutoJoinDomain(ctx, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAutoJoinDomain", reflect.TypeOf((*MockOrgStore)(nil).GetByAutoJoinDomain), ctx, domain)
}

// GetByID mocks base method.
func (m *MockOrgStore) GetByID(ctx *gofr.Context, id int64) (*models.Org, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Org)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOrgStoreMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOrgStore)(nil).GetByID), ctx, id)
}

// SlugExists mocks base method.
func (m *MockOrgStore) SlugExists(ctx *gofr.Context, slug string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SlugExists", ctx, slug)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SlugExists indicates an expected call of SlugExists.
func (mr *MockOrgStoreMockRecorder) SlugExists(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SlugExists", reflect.TypeOf((*MockOrgStore)(nil).SlugExists), ctx, slug)
}

// Update mocks base method.
func (m *MockOrgStore) Update(ctx *gofr.Context, id int64, name string, autoJoinDomain *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, name, autoJoinDomain)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOrgStoreMockRecorder) Update(ctx, id, name, autoJoinDomain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrgStore)(nil).Update), ctx, id, name, autoJoinDomain)
}

// MockMemberStore is a mock of MemberStore interface.
type MockMemberStore struct {
	ctrl     *gomock.Controller
	recorder *MockMemberStoreMockRecorder
	isgomock struct{}
}

// MockMemberStoreMockRecorder is the mock recorder for MockMemberStore.
type MockMemberStoreMockRecorder struct {
	mock *MockMemberStore
}

// NewMockMemberStore creates a new mock instance.
func NewMockMemberStore(ctrl *gomock.Controller) *MockMemberStore {
	mock := &MockMemberStore{ctrl: ctrl}
	mock.recorder = &MockMemberStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberStore) EXPECT() *MockMemberStoreMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockMemberStore) Add(ctx *gofr.Context, orgID, userID int64, role string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, orgID, userID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockMemberStoreMockRecorder) Add(ctx, orgID, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockMemberStore)(nil).Add), ctx, orgID, userID, role)
}

// CountOwners mocks base method.
func (m *MockMemberStore) CountOwners(ctx *gofr.Context, orgID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOwners", ctx, orgID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOwners indicates an expected call of CountOwners.
func (mr *MockMemberStoreMockRecorder) CountOwners(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOwners", reflect.TypeOf((*MockMemberStore)(nil).CountOwners), ctx, orgID)
}

// GetRole mocks base method.
func (m *MockMemberStore) GetRole(ctx *gofr.Context, orgID, userID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", ctx, orgID, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockMemberStoreMockRecorder) GetRole(ctx, orgID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockMemberStore)(nil).GetRole), ctx, orgID, userID)
}

// ListMembers mocks base method.
func (m *MockMemberStore) ListMembers(ctx *gofr.Context, orgID int64) ([]models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, orgID)
	ret0, _ := ret[0].([]models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockMemberStoreMockRecorder) ListMembers(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockMemberStore)(nil).ListMembers), ctx, orgID)
}

// ListOrgsForUser mocks base method.
func (m *MockMemberStore) ListOrgsForUser(ctx *gofr.Context, userID int64) ([]models.OrgMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrgsForUser", ctx, userID)
	ret0, _ := ret[0].([]models.OrgMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrgsForUser indicates an expected call of ListOrgsForUser.
func (mr *MockMemberStoreMockRecorder) ListOrgsForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrgsForUser", reflect.TypeOf((*MockMemberStore)(nil).ListOrgsForUser), ctx, userID)
}

// Remove mocks base method.
func (m *MockMemberStore) Remove(ctx *gofr.Context, orgID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, orgID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockMemberStoreMockRecorder) Remove(ctx, orgID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockMemberStore)(nil).Remove), ctx, orgID, userID)
}

// MockInviteStore is a mock of InviteStore interface.
type MockInviteStore struct {
	ctrl     *gomock.Controller
	recorder *MockInviteStoreMockRecorder
	isgomock struct{}
}

// MockInviteStoreMockRecorder is the mock recorder for MockInviteStore.
type MockInviteStoreMockRecorder struct {
	mock *MockInviteStore
}

// NewMockInviteStore creates a new mock instance.
func NewMockInviteStore(ctrl *gomock.Controller) *MockInviteStore {
	mock := &MockInviteStore{ctrl: ctrl}
	mock.recorder = &MockInviteStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInviteStore) EXPECT() *MockInviteStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInviteStore) Create(ctx *gofr.Context, orgID int64, email string, invitedBy int64) (*models.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, orgID, email, invitedBy)
	ret0, _ := ret[0].(*models.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInviteStoreMockRecorder) Create(ctx, orgID, email, invitedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInviteStore)(nil).Create), ctx, orgID, email, invitedBy)
}

// GetByID mocks base method.
func (m *MockInviteStore) GetByID(ctx *gofr.Context, orgID, id int64) (*models.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, orgID, id)
	ret0, _ := ret[0].(*models.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockInviteStoreMockRecorder) GetByID(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockInviteStore)(nil).GetByID), ctx, orgID, id)
}

// HasPending mocks base method.
func (m *MockInviteStore) HasPending(ctx *gofr.Context, orgID int64, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPending", ctx, orgID, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPending indicates an expected call of HasPending.
func (mr *MockInviteStoreMockRecorder) HasPending(ctx, orgID, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPending", reflect.TypeOf((*MockInviteStore)(nil).HasPending), ctx, orgID, email)
}

// ListPending mocks base method.
func (m *MockInviteStore) ListPending(ctx *gofr.Context, orgID int64) ([]models.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", ctx, orgID)
	ret0, _ := ret[0].([]models.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPending indicates an expected call of ListPending.
func (mr *MockInviteStoreMockRecorder) ListPending(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockInviteStore)(nil).ListPending), ctx, orgID)
}

// PendingForEmail mocks base method.
func (m *MockInviteStore) PendingForEmail(ctx *gofr.Context, email string) ([]models.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingForEmail", ctx, email)
	ret0, _ := ret[0].([]models.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingForEmail indicates an expected call of PendingForEmail.
func (mr *MockInviteStoreMockRecorder) PendingForEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingForEmail", reflect.TypeOf((*MockInviteStore)(nil).PendingForEmail), ctx, email)
}

// SetStatus mocks base method.
func (m *MockInviteStore) SetStatus(ctx *gofr.Context, id int64, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockInviteStoreMockRecorder) SetStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockInviteStore)(nil).SetStatus), ctx, id, status)
}

// MockTokenIssuer is a mock of TokenIssuer interface.
type MockTokenIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockTokenIssuerMockRecorder
	isgomock struct{}
}

// MockTokenIssuerMockRecorder is the mock recorder for MockTokenIssuer.
type MockTokenIssuerMockRecorder struct {
	mock *MockTokenIssuer
}

// NewMockTokenIssuer creates a new mock instance.
func NewMockTokenIssuer(ctrl *gomock.Controller) *MockTokenIssuer {
	mock := &MockTokenIssuer{ctrl: ctrl}
	mock.recorder = &MockTokenIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenIssuer) EXPECT() *MockTokenIssuerMockRecorder {
	return m.recorder
}

// IssuePair mocks base method.
func (m *MockTokenIssuer) IssuePair(userID, orgID int64, role string) (models.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssuePair", userID, orgID, role)
	ret0, _ := ret[0].(models.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssuePair indicates an expected call of IssuePair.
func (mr *MockTokenIssuerMockRecorder) IssuePair(userID, orgID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssuePair", reflect.TypeOf((*MockTokenIssuer)(nil).IssuePair), userID, orgID, role)
}

// Parse mocks base method.
func (m *MockTokenIssuer) Parse(raw, wantType string) (*auth.SessionClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", raw, wantType)
	ret0, _ := ret[0].(*auth.SessionClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockTokenIssuerMockRecorder) Parse(raw, wantType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockTokenIssuer)(nil).Parse), raw, wantType)
}

// MockLinkStore is a mock of LinkStore interface.
type MockLinkStore struct {
	ctrl     *gomock.Controller
	recorder *MockLinkStoreMockRecorder
	isgomock struct{}
}

// MockLinkStoreMockRecorder is the mock recorder for MockLinkStore.
type MockLinkStoreMockRecorder struct {
	mock *MockLinkStore
}

// NewMockLinkStore creates a new mock instance.
func NewMockLinkStore(ctrl *gomock.Controller) *MockLinkStore {
	mock := &MockLinkStore{ctrl: ctrl}
	mock.recorder = &MockLinkStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkStore) EXPECT() *MockLinkStoreMockRecorder {
	return m.recorder
}

// CodeExists mocks base method.
func (m *MockLinkStore) CodeExists(ctx *gofr.Context, code string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CodeExists", ctx, code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CodeExists indicates an expected call of CodeExists.
func (mr *MockLinkStoreMockRecorder) CodeExists(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CodeExists", reflect.TypeOf((*MockLinkStore)(nil).CodeExists), ctx, code)
}

// Count mocks base method.
func (m *MockLinkStore) Count(ctx *gofr.Context, orgID, viewerID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, orgID, viewerID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockLinkStoreMockRecorder) Count(ctx, orgID, viewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockLinkStore)(nil).Count), ctx, orgID, viewerID)
}

// Create mocks base method.
func (m *MockLinkStore) Create(ctx *gofr.Context, l *models.Link) (*models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, l)
	ret0, _ := ret[0].(*models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLinkStoreMockRecorder) Create(ctx, l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLinkStore)(nil).Create), ctx, l)
}

// FindByDestination mocks base method.
func (m *MockLinkStore) FindByDestination(ctx *gofr.Context, orgID, viewerID int64, destinationURL string) (*models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDestination", ctx, orgID, viewerID, destinationURL)
	ret0, _ := ret[0].(*models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDestination indicates an expected call of FindByDestination.
func (mr *MockLinkStoreMockRecorder) FindByDestination(ctx, orgID, viewerID, destinationURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDestination", reflect.TypeOf((*MockLinkStore)(nil).FindByDestination), ctx, orgID, viewerID, destinationURL)
}

// GetByCode mocks base method.
func (m *MockLinkStore) GetByCode(ctx *gofr.Context, code string) (*models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockLinkStoreMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockLinkStore)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockLinkStore) GetByID(ctx *gofr.Context, orgID, id int64) (*models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, orgID, id)
	ret0, _ := ret[0].(*models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockLinkStoreMockRecorder) GetByID(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockLinkStore)(nil).GetByID), ctx, orgID, id)
}

// InsertEdit mocks base method.
func (m *MockLinkStore) InsertEdit(ctx *gofr.Context, e *models.LinkEdit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEdit", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEdit indicates an expected call of InsertEdit.
func (mr *MockLinkStoreMockRecorder) InsertEdit(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEdit", reflect.TypeOf((*MockLinkStore)(nil).InsertEdit), ctx, e)
}

// List mocks base method.
func (m *MockLinkStore) List(ctx *gofr.Context, orgID, viewerID int64, limit, offset int) ([]models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, orgID, viewerID, limit, offset)
	ret0, _ := ret[0].([]models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockLinkStoreMockRecorder) List(ctx, orgID, viewerID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLinkStore)(nil).List), ctx, orgID, viewerID, limit, offset)
}

// ListActiveClickedSince mocks base method.
func (m *MockLinkStore) ListActiveClickedSince(ctx *gofr.Context, since string, afterID int64, limit int) ([]models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveClickedSince", ctx, since, afterID, limit)
	ret0, _ := ret[0].([]models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveClickedSince indicates an expected call of ListActiveClickedSince.
func (mr *MockLinkStoreMockRecorder) ListActiveClickedSince(ctx, since, afterID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveClickedSince", reflect.TypeOf((*MockLinkStore)(nil).ListActiveClickedSince), ctx, since, afterID, limit)
}

// RecordVisit mocks base method.
func (m *MockLinkStore) RecordVisit(ctx *gofr.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordVisit", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordVisit indicates an expected call of RecordVisit.
func (mr *MockLinkStoreMockRecorder) RecordVisit(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordVisit", reflect.TypeOf((*MockLinkStore)(nil).RecordVisit), ctx, id)
}

// SetStatusByID mocks base method.
func (m *MockLinkStore) SetStatusByID(ctx *gofr.Context, id int64, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatusByID", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatusByID indicates an expected call of SetStatusByID.
func (mr *MockLinkStoreMockRecorder) SetStatusByID(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatusByID", reflect.TypeOf((*MockLinkStore)(nil).SetStatusByID), ctx, id, status)
}

// UpdateCode mocks base method.
func (m *MockLinkStore) UpdateCode(ctx *gofr.Context, orgID, id int64, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCode", ctx, orgID, id, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCode indicates an expected call of UpdateCode.
func (mr *MockLinkStoreMockRecorder) UpdateCode(ctx, orgID, id, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCode", reflect.TypeOf((*MockLinkStore)(nil).UpdateCode), ctx, orgID, id, code)
}

// UpdateDeeplink mocks base method.
func (m *MockLinkStore) UpdateDeeplink(ctx *gofr.Context, orgID, id int64, cfg *models.DeeplinkConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeeplink", ctx, orgID, id, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeeplink indicates an expected call of UpdateDeeplink.
func (mr *MockLinkStoreMockRecorder) UpdateDeeplink(ctx, orgID, id, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeeplink", reflect.TypeOf((*MockLinkStore)(nil).UpdateDeeplink), ctx, orgID, id, cfg)
}

// UpdateDestination mocks base method.
func (m *MockLinkStore) UpdateDestination(ctx *gofr.Context, orgID, id int64, destinationURL string, utmSource, utmMedium, utmCampaign *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDestination", ctx, orgID, id, destinationURL, utmSource, utmMedium, utmCampaign)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDestination indicates an expected call of UpdateDestination.
func (mr *MockLinkStoreMockRecorder) UpdateDestination(ctx, orgID, id, destinationURL, utmSource, utmMedium, utmCampaign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDestination", reflect.TypeOf((*MockLinkStore)(nil).UpdateDestination), ctx, orgID, id, destinationURL, utmSource, utmMedium, utmCampaign)
}

// MockURLScanner is a mock of URLScanner interface.
type MockURLScanner struct {
	ctrl     *gomock.Controller
	recorder *MockURLScannerMockRecorder
	isgomock struct{}
}

// MockURLScannerMockRecorder is the mock recorder for MockURLScanner.
type MockURLScannerMockRecorder struct {
	mock *MockURLScanner
}

// NewMockURLScanner creates a new mock instance.
func NewMockURLScanner(ctrl *gomock.Controller) *MockURLScanner {
	mock := &MockURLScanner{ctrl: ctrl}
	mock.recorder = &MockURLScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLScanner) EXPECT() *MockURLScannerMockRecorder {
	return m.recorder
}

// Scan mocks base method.
func (m *MockURLScanner) Scan(ctx context.Context, rawURL string) (scanner.Verdict, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scan", ctx, rawURL)
	ret0, _ := ret[0].(scanner.Verdict)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scan indicates an expected call of Scan.
func (mr *MockURLScannerMockRecorder) Scan(ctx, rawURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockURLScanner)(nil).Scan), ctx, rawURL)
}

// MockAbuseReportStore is a mock of AbuseReportStore interface.
type MockAbuseReportStore struct {
	ctrl     *gomock.Controller
	recorder *MockAbuseReportStoreMockRecorder
	isgomock struct{}
}

// MockAbuseReportStoreMockRecorder is the mock recorder for MockAbuseReportStore.
type MockAbuseReportStoreMockRecorder struct {
	mock *MockAbuseReportStore
}

// NewMockAbuseReportStore creates a new mock instance.
func NewMockAbuseReportStore(ctrl *gomock.Controller) *MockAbuseReportStore {
	mock := &MockAbuseReportStore{ctrl: ctrl}
	mock.recorder = &MockAbuseReportStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAbuseReportStore) EXPECT() *MockAbuseReportStoreMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockAbuseReportStore) Insert(ctx *gofr.Context, r *models.AbuseReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockAbuseReportStoreMockRecorder) Insert(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockAbuseReportStore)(nil).Insert), ctx, r)
}

// MockAPIKeyStore is a mock of APIKeyStore interface.
type MockAPIKeyStore struct {
	ctrl     *gomock.Controller
	recorder *MockAPIKeyStoreMockRecorder
	isgomock struct{}
}

// MockAPIKeyStoreMockRecorder is the mock recorder for MockAPIKeyStore.
type MockAPIKeyStoreMockRecorder struct {
	mock *MockAPIKeyStore
}

// NewMockAPIKeyStore creates a new mock instance.
func NewMockAPIKeyStore(ctrl *gomock.Controller) *MockAPIKeyStore {
	mock := &MockAPIKeyStore{ctrl: ctrl}
	mock.recorder = &MockAPIKeyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIKeyStore) EXPECT() *MockAPIKeyStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAPIKeyStore) Create(ctx *gofr.Context, orgID int64, name, keyHash, keyHint string) (*models.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, orgID, name, keyHash, keyHint)
	ret0, _ := ret[0].(*models.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAPIKeyStoreMockRecorder) Create(ctx, orgID, name, keyHash, keyHint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAPIKeyStore)(nil).Create), ctx, orgID, name, keyHash, keyHint)
}

// Disable mocks base method.
func (m *MockAPIKeyStore) Disable(ctx *gofr.Context, orgID, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable", ctx, orgID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disable indicates an expected call of Disable.
func (mr *MockAPIKeyStoreMockRecorder) Disable(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockAPIKeyStore)(nil).Disable), ctx, orgID, id)
}

// GetByHash mocks base method.
func (m *MockAPIKeyStore) GetByHash(ctx *gofr.Context, keyHash string) (*models.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHash", ctx, keyHash)
	ret0, _ := ret[0].(*models.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHash indicates an expected call of GetByHash.
func (mr *MockAPIKeyStoreMockRecorder) GetByHash(ctx, keyHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHash", reflect.TypeOf((*MockAPIKeyStore)(nil).GetByHash), ctx, keyHash)
}

// GetByID mocks base method.
func (m *MockAPIKeyStore) GetByID(ctx *gofr.Context, orgID, id int64) (*models.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, orgID, id)
	ret0, _ := ret[0].(*models.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAPIKeyStoreMockRecorder) GetByID(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAPIKeyStore)(nil).GetByID), ctx, orgID, id)
}

// List mocks base method.
func (m *MockAPIKeyStore) List(ctx *gofr.Context, orgID int64) ([]models.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, orgID)
	ret0, _ := ret[0].([]models.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAPIKeyStoreMockRecorder) List(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAPIKeyStore)(nil).List), ctx, orgID)
}

// TouchLastUsed mocks base method.
func (m *MockAPIKeyStore) TouchLastUsed(ctx *gofr.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchLastUsed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchLastUsed indicates an expected call of TouchLastUsed.
func (mr *MockAPIKeyStoreMockRecorder) TouchLastUsed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchLastUsed", reflect.TypeOf((*MockAPIKeyStore)(nil).TouchLastUsed), ctx, id)
}

// MockDomainStore is a mock of DomainStore interface.
type MockDomainStore struct {
	ctrl     *gomock.Controller
	recorder *MockDomainStoreMockRecorder
	isgomock struct{}
}

// MockDomainStoreMockRecorder is the mock recorder for MockDomainStore.
type MockDomainStoreMockRecorder struct {
	mock *MockDomainStore
}

// NewMockDomainStore creates a new mock instance.
func NewMockDomainStore(ctrl *gomock.Controller) *MockDomainStore {
	mock := &MockDomainStore{ctrl: ctrl}
	mock.recorder = &MockDomainStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomainStore) EXPECT() *MockDomainStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDomainStore) Create(ctx *gofr.Context, orgID int64, hostname, verificationToken string) (*models.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, orgID, hostname, verificationToken)
	ret0, _ := ret[0].(*models.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDomainStoreMockRecorder) Create(ctx, orgID, hostname, verificationToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDomainStore)(nil).Create), ctx, orgID, hostname, verificationToken)
}

// Delete mocks base method.
func (m *MockDomainStore) Delete(ctx *gofr.Context, orgID, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, orgID, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDomainStoreMockRecorder) Delete(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDomainStore)(nil).Delete), ctx, orgID, id)
}

// GetByHostname mocks base method.
func (m *MockDomainStore) GetByHostname(ctx *gofr.Context, hostname string) (*models.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHostname", ctx, hostname)
	ret0, _ := ret[0].(*models.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHostname indicates an expected call of GetByHostname.
func (mr *MockDomainStoreMockRecorder) GetByHostname(ctx, hostname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHostname", reflect.TypeOf((*MockDomainStore)(nil).GetByHostname), ctx, hostname)
}

// GetByID mocks base method.
func (m *MockDomainStore) GetByID(ctx *gofr.Context, orgID, id int64) (*models.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, orgID, id)
	ret0, _ := ret[0].(*models.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDomainStoreMockRecorder) GetByID(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDomainStore)(nil).GetByID), ctx, orgID, id)
}

// HasVerified mocks base method.
func (m *MockDomainStore) HasVerified(ctx *gofr.Context, orgID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasVerified", ctx, orgID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasVerified indicates an expected call of HasVerified.
func (mr *MockDomainStoreMockRecorder) HasVerified(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasVerified", reflect.TypeOf((*MockDomainStore)(nil).HasVerified), ctx, orgID)
}

// ListByOrg mocks base method.
func (m *MockDomainStore) ListByOrg(ctx *gofr.Context, orgID int64) ([]models.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOrg", ctx, orgID)
	ret0, _ := ret[0].([]models.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByOrg indicates an expected call of ListByOrg.
func (mr *MockDomainStoreMockRecorder) ListByOrg(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOrg", reflect.TypeOf((*MockDomainStore)(nil).ListByOrg), ctx, orgID)
}

// PrimaryVerifiedHostname mocks base method.
func (m *MockDomainStore) PrimaryVerifiedHostname(ctx *gofr.Context, orgID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrimaryVerifiedHostname", ctx, orgID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrimaryVerifiedHostname indicates an expected call of PrimaryVerifiedHostname.
func (mr *MockDomainStoreMockRecorder) PrimaryVerifiedHostname(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrimaryVerifiedHostname", reflect.TypeOf((*MockDomainStore)(nil).PrimaryVerifiedHostname), ctx, orgID)
}

// SetPrimary mocks base method.
func (m *MockDomainStore) SetPrimary(ctx *gofr.Context, orgID, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPrimary", ctx, orgID, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetPrimary indicates an expected call of SetPrimary.
func (mr *MockDomainStoreMockRecorder) SetPrimary(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrimary", reflect.TypeOf((*MockDomainStore)(nil).SetPrimary), ctx, orgID, id)
}

// SetVerified mocks base method.
func (m *MockDomainStore) SetVerified(ctx *gofr.Context, orgID, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVerified", ctx, orgID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetVerified indicates an expected call of SetVerified.
func (mr *MockDomainStoreMockRecorder) SetVerified(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVerified", reflect.TypeOf((*MockDomainStore)(nil).SetVerified), ctx, orgID, id)
}

// MockDNSResolver is a mock of DNSResolver interface.
type MockDNSResolver struct {
	ctrl     *gomock.Controller
	recorder *MockDNSResolverMockRecorder
	isgomock struct{}
}

// MockDNSResolverMockRecorder is the mock recorder for MockDNSResolver.
type MockDNSResolverMockRecorder struct {
	mock *MockDNSResolver
}

// NewMockDNSResolver creates a new mock instance.
func NewMockDNSResolver(ctrl *gomock.Controller) *MockDNSResolver {
	mock := &MockDNSResolver{ctrl: ctrl}
	mock.recorder = &MockDNSResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDNSResolver) EXPECT() *MockDNSResolverMockRecorder {
	return m.recorder
}

// LookupTXT mocks base method.
func (m *MockDNSResolver) LookupTXT(ctx context.Context, name string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupTXT", ctx, name)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupTXT indicates an expected call of LookupTXT.
func (mr *MockDNSResolverMockRecorder) LookupTXT(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupTXT", reflect.TypeOf((*MockDNSResolver)(nil).LookupTXT), ctx, name)
}

// MockClickStore is a mock of ClickStore interface.
type MockClickStore struct {
	ctrl     *gomock.Controller
	recorder *MockClickStoreMockRecorder
	isgomock struct{}
}

// MockClickStoreMockRecorder is the mock recorder for MockClickStore.
type MockClickStoreMockRecorder struct {
	mock *MockClickStore
}

// NewMockClickStore creates a new mock instance.
func NewMockClickStore(ctrl *gomock.Controller) *MockClickStore {
	mock := &MockClickStore{ctrl: ctrl}
	mock.recorder = &MockClickStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickStore) EXPECT() *MockClickStoreMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockClickStore) Insert(ctx *gofr.Context, c *models.Click) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockClickStoreMockRecorder) Insert(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockClickStore)(nil).Insert), ctx, c)
}

// MockStatsStore is a mock of StatsStore interface.
type MockStatsStore struct {
	ctrl     *gomock.Controller
	recorder *MockStatsStoreMockRecorder
	isgomock struct{}
}

// MockStatsStoreMockRecorder is the mock recorder for MockStatsStore.
type MockStatsStoreMockRecorder struct {
	mock *MockStatsStore
}

// NewMockStatsStore creates a new mock instance.
func NewMockStatsStore(ctrl *gomock.Controller) *MockStatsStore {
	mock := &MockStatsStore{ctrl: ctrl}
	mock.recorder = &MockStatsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsStore) EXPECT() *MockStatsStoreMockRecorder {
	return m.recorder
}

// BrowserPerDay mocks base method.
func (m *MockStatsStore) BrowserPerDay(ctx *gofr.Context, orgID, linkID int64, from, to string) ([]models.DayDimCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BrowserPerDay", ctx, orgID, linkID, from, to)
	ret0, _ := ret[0].([]models.DayDimCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BrowserPerDay indicates an expected call of BrowserPerDay.
func (mr *MockStatsStoreMockRecorder) BrowserPerDay(ctx, orgID, linkID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BrowserPerDay", reflect.TypeOf((*MockStatsStore)(nil).BrowserPerDay), ctx, orgID, linkID, from, to)
}

// BrowserTotals mocks base method.
func (m *MockStatsStore) BrowserTotals(ctx *gofr.Context, orgID, linkID int64, from, to string) ([]models.DimCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BrowserTotals", ctx, orgID, linkID, from, to)
	ret0, _ := ret[0].([]models.DimCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BrowserTotals indicates an expected call of BrowserTotals.
func (mr *MockStatsStoreMockRecorder) BrowserTotals(ctx, orgID, linkID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BrowserTotals", reflect.TypeOf((*MockStatsStore)(nil).BrowserTotals), ctx, orgID, linkID, from, to)
}

// CityPerDay mocks base method.
func (m *MockStatsStore) CityPerDay(ctx *gofr.Context, orgID, linkID int64, from, to string) ([]models.DayDimCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CityPerDay", ctx, orgID, linkID, from, to)
	ret0, _ := ret[0].([]models.DayDimCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CityPerDay indicates an expected call of CityPerDay.
func (mr *MockStatsStoreMockRecorder) CityPerDay(ctx, orgID, linkID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CityPerDay", reflect.TypeOf((*MockStatsStore)(nil).CityPerDay), ctx, orgID, linkID, from, to)
}

// CityTotals mocks base method.
func (m *MockStatsStore) CityTotals(ctx *gofr.Context, orgID, linkID int64, from, to string) ([]models.DimCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CityTotals", ctx, orgID, linkID, from, to)
	ret0, _ := ret[0].([]models.DimCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CityTotals indicates an expected call of CityTotals.
func (mr *MockStatsStoreMockRecorder) CityTotals(ctx, orgID, linkID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CityTotals", reflect.TypeOf((*MockStatsStore)(nil).CityTotals), ctx, orgID, linkID, from, to)
}

// ClickDetails mocks base method.
func (m *MockStatsStore) ClickDetails(ctx *gofr.Context, orgID, linkID int64, from, to string) ([]models.ClickDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClickDetails", ctx, orgID, linkID, from, to)
	ret0, _ := ret[0].([]models.ClickDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClickDetails indicates an expected call of ClickDetails.
func (mr *MockStatsStoreMockRecorder) ClickDetails(ctx, orgID, linkID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClickDetails", reflect.TypeOf((*MockStatsStore)(nil).ClickDetails), ctx, orgID, linkID, from, to)
}

// ClicksPerDay mocks base method.
func (m *MockStatsStore) ClicksPerDay(ctx *gofr.Context, orgID, linkID int64, from, to string) ([]models.DayCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClicksPerDay", ctx, orgID, linkID, from, to)
	ret0, _ := ret[0].([]models.DayCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClicksPerDay indicates an expected call of ClicksPerDay.
func (mr *MockStatsStoreMockRecorder) ClicksPerDay(ctx, orgID, linkID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClicksPerDay", reflect.TypeOf((*MockStatsStore)(nil).ClicksPerDay), ctx, orgID, linkID, from, to)
}

// CountryPerDay mocks base method.
func (m *MockStatsStore) CountryPerDay(ctx *gofr.Context, orgID, linkID int64, from, to string) ([]models.DayDimCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountryPerDay", ctx, orgID, linkID, from, to)
	ret0, _ := ret[0].([]models.DayDimCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountryPerDay indicates an expected call of CountryPerDay.
func (mr *MockStatsStoreMockRecorder) CountryPerDay(ctx, orgID, linkID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountryPerDay", reflect.TypeOf((*MockStatsStore)(nil).CountryPerDay), ctx, orgID, linkID, from, to)
}

// CountryTotals mocks base method.
func (m *MockStatsStore) CountryTotals(ctx *gofr.Context, orgID, linkID int64, from, to string) ([]models.DimCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountryTotals", ctx, orgID, linkID, from, to)
	ret0, _ := ret[0].([]models.DimCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountryTotals indicates an expected call of CountryTotals.
func (mr *MockStatsStoreMockRecorder) CountryTotals(ctx, orgID, linkID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountryTotals", reflect.TypeOf((*MockStatsStore)(nil).CountryTotals), ctx, orgID, linkID, from, to)
}

// DeeplinkClickCount mocks base method.
func (m *MockStatsStore) DeeplinkClickCount(ctx *gofr.Context, orgID, linkID int64, from, to string, isDeeplink bool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeeplinkClickCount", ctx, orgID, linkID, from, to, isDeeplink)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeeplinkClickCount indicates an expected call of DeeplinkClickCount.
func (mr *MockStatsStoreMockRecorder) DeeplinkClickCount(ctx, orgID, linkID, from, to, isDeeplink any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeeplinkClickCount", reflect.TypeOf((*MockStatsStore)(nil).DeeplinkClickCount), ctx, orgID, linkID, from, to, isDeeplink)
}

// DevicePerDay mocks base method.
func (m *MockStatsStore) DevicePerDay(ctx *gofr.Context, orgID, linkID int64, from, to string) ([]models.DayDimCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DevicePerDay", ctx, orgID, linkID, from, to)
	ret0, _ := ret[0].([]models.DayDimCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DevicePerDay indicates an expected call of DevicePerDay.
func (mr *MockStatsStoreMockRecorder) DevicePerDay(ctx, orgID, linkID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DevicePerDay", reflect.TypeOf((*MockStatsStore)(nil).DevicePerDay), ctx, orgID, linkID, from, to)
}

// DeviceTotals mocks base method.
func (m *MockStatsStore) DeviceTotals(ctx *gofr.Context, orgID, linkID int64, from, to string) ([]models.DimCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceTotals", ctx, orgID, linkID, from, to)
	ret0, _ := ret[0].([]models.DimCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeviceTotals indicates an expected call of DeviceTotals.
func (mr *MockStatsStoreMockRecorder) DeviceTotals(ctx, orgID, linkID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceTotals", reflect.TypeOf((*MockStatsStore)(nil).DeviceTotals), ctx, orgID, linkID, from, to)
}

// DistinctTags mocks base method.
func (m *MockStatsStore) DistinctTags(ctx *gofr.Context, orgID int64, since string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DistinctTags", ctx, orgID, since)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DistinctTags indicates an expected call of DistinctTags.
func (mr *MockStatsStoreMockRecorder) DistinctTags(ctx, orgID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistinctTags", reflect.TypeOf((*MockStatsStore)(nil).DistinctTags), ctx, orgID, since)
}

// MobileOSPerDay mocks base method.
func (m *MockStatsStore) MobileOSPerDay(ctx *gofr.Context, orgID, linkID int64, from, to string) ([]models.DayDimCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MobileOSPerDay", ctx, orgID, linkID, from, to)
	ret0, _ := ret[0].([]models.DayDimCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MobileOSPerDay indicates an expected call of MobileOSPerDay.
func (mr *MockStatsStoreMockRecorder) MobileOSPerDay(ctx, orgID, linkID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MobileOSPerDay", reflect.TypeOf((*MockStatsStore)(nil).MobileOSPerDay), ctx, orgID, linkID, from, to)
}

// MobileOSTotals mocks base method.
func (m *MockStatsStore) MobileOSTotals(ctx *gofr.Context, orgID, linkID int64, from, to string) ([]models.DimCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MobileOSTotals", ctx, orgID, linkID, from, to)
	ret0, _ := ret[0].([]models.DimCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MobileOSTotals indicates an expected call of MobileOSTotals.
func (mr *MockStatsStoreMockRecorder) MobileOSTotals(ctx, orgID, linkID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MobileOSTotals", reflect.TypeOf((*MockStatsStore)(nil).MobileOSTotals), ctx, orgID, linkID, from, to)
}

// ReferrerPerDay mocks base method.
func (m *MockStatsStore) ReferrerPerDay(ctx *gofr.Context, orgID, linkID int64, from, to string) ([]models.DayDimCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReferrerPerDay", ctx, orgID, linkID, from, to)
	ret0, _ := ret[0].([]models.DayDimCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReferrerPerDay indicates an expected call of ReferrerPerDay.
func (mr *MockStatsStoreMockRecorder) ReferrerPerDay(ctx, orgID, linkID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReferrerPerDay", reflect.TypeOf((*MockStatsStore)(nil).ReferrerPerDay), ctx, orgID, linkID, from, to)
}

// ReferrerTotals mocks base method.
func (m *MockStatsStore) ReferrerTotals(ctx *gofr.Context, orgID, linkID int64, from, to string) ([]models.DimCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReferrerTotals", ctx, orgID, linkID, from, to)
	ret0, _ := ret[0].([]models.DimCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReferrerTotals indicates an expected call of ReferrerTotals.
func (mr *MockStatsStoreMockRecorder) ReferrerTotals(ctx, orgID, linkID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReferrerTotals", reflect.TypeOf((*MockStatsStore)(nil).ReferrerTotals), ctx, orgID, linkID, from, to)
}

// RegionPerDay mocks base method.
func (m *MockStatsStore) RegionPerDay(ctx *gofr.Context, orgID, linkID int64, from, to string) ([]models.DayDimCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegionPerDay", ctx, orgID, linkID, from, to)
	ret0, _ := ret[0].([]models.DayDimCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegionPerDay indicates an expected call of RegionPerDay.
func (mr *MockStatsStoreMockRecorder) RegionPerDay(ctx, orgID, linkID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegionPerDay", reflect.TypeOf((*MockStatsStore)(nil).RegionPerDay), ctx, orgID, linkID, from, to)
}

// RegionTotals mocks base method.
func (m *MockStatsStore) RegionTotals(ctx *gofr.Context, orgID, linkID int64, from, to string) ([]models.DimCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegionTotals", ctx, orgID, linkID, from, to)
	ret0, _ := ret[0].([]models.DimCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegionTotals indicates an expected call of RegionTotals.
func (mr *MockStatsStoreMockRecorder) RegionTotals(ctx, orgID, linkID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegionTotals", reflect.TypeOf((*MockStatsStore)(nil).RegionTotals), ctx, orgID, linkID, from, to)
}

// TargetMatchedCount mocks base method.
func (m *MockStatsStore) TargetMatchedCount(ctx *gofr.Context, orgID, linkID int64, from, to string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TargetMatchedCount", ctx, orgID, linkID, from, to)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TargetMatchedCount indicates an expected call of TargetMatchedCount.
func (mr *MockStatsStoreMockRecorder) TargetMatchedCount(ctx, orgID, linkID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TargetMatchedCount", reflect.TypeOf((*MockStatsStore)(nil).TargetMatchedCount), ctx, orgID, linkID, from, to)
}

// TotalClicks mocks base method.
func (m *MockStatsStore) TotalClicks(ctx *gofr.Context, orgID, linkID int64, from, to string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TotalClicks", ctx, orgID, linkID, from, to)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TotalClicks indicates an expected call of TotalClicks.
func (mr *MockStatsStoreMockRecorder) TotalClicks(ctx, orgID, linkID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TotalClicks", reflect.TypeOf((*MockStatsStore)(nil).TotalClicks), ctx, orgID, linkID, from, to)
}

// UTMCampaignCounts mocks base method.
func (m *MockStatsStore) UTMCampaignCounts(ctx *gofr.Context, orgID, viewerID int64, since string) ([]models.UTMCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UTMCampaignCounts", ctx, orgID, viewerID, since)
	ret0, _ := ret[0].([]models.UTMCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UTMCampaignCounts indicates an expected call of UTMCampaignCounts.
func (mr *MockStatsStoreMockRecorder) UTMCampaignCounts(ctx, orgID, viewerID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UTMCampaignCounts", reflect.TypeOf((*MockStatsStore)(nil).UTMCampaignCounts), ctx, orgID, viewerID, since)
}

// UTMMediumCounts mocks base method.
func (m *MockStatsStore) UTMMediumCounts(ctx *gofr.Context, orgID, viewerID int64, since string) ([]models.UTMCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UTMMediumCounts", ctx, orgID, viewerID, since)
	ret0, _ := ret[0].([]models.UTMCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UTMMediumCounts indicates an expected call of UTMMediumCounts.
func (mr *MockStatsStoreMockRecorder) UTMMediumCounts(ctx, orgID, viewerID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UTMMediumCounts", reflect.TypeOf((*MockStatsStore)(nil).UTMMediumCounts), ctx, orgID, viewerID, since)
}

// UTMSourceCounts mocks base method.
func (m *MockStatsStore) UTMSourceCounts(ctx *gofr.Context, orgID, viewerID int64, since string) ([]models.UTMCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UTMSourceCounts", ctx, orgID, viewerID, since)
	ret0, _ := ret[0].([]models.UTMCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UTMSourceCounts indicates an expected call of UTMSourceCounts.
func (mr *MockStatsStoreMockRecorder) UTMSourceCounts(ctx, orgID, viewerID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UTMSourceCounts", reflect.TypeOf((*MockStatsStore)(nil).UTMSourceCounts), ctx, orgID, viewerID, since)
}

// UniqueTagClicks mocks base method.
func (m *MockStatsStore) UniqueTagClicks(ctx *gofr.Context, orgID int64, linkIDs []int64, since string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UniqueTagClicks", ctx, orgID, linkIDs, since)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UniqueTagClicks indicates an expected call of UniqueTagClicks.
func (mr *MockStatsStoreMockRecorder) UniqueTagClicks(ctx, orgID, linkIDs, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UniqueTagClicks", reflect.TypeOf((*MockStatsStore)(nil).UniqueTagClicks), ctx, orgID, linkIDs, since)
}

// MockUsageReader is a mock of UsageReader interface.
type MockUsageReader struct {
	ctrl     *gomock.Controller
	recorder *MockUsageReaderMockRecorder
	isgomock struct{}
}

// MockUsageReaderMockRecorder is the mock recorder for MockUsageReader.
type MockUsageReaderMockRecorder struct {
	mock *MockUsageReader
}

// NewMockUsageReader creates a new mock instance.
func NewMockUsageReader(ctrl *gomock.Controller) *MockUsageReader {
	mock := &MockUsageReader{ctrl: ctrl}
	mock.recorder = &MockUsageReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageReader) EXPECT() *MockUsageReaderMockRecorder {
	return m.recorder
}

// EventsThisMonth mocks base method.
func (m *MockUsageReader) EventsThisMonth(ctx *gofr.Context, orgID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventsThisMonth", ctx, orgID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EventsThisMonth indicates an expected call of EventsThisMonth.
func (mr *MockUsageReaderMockRecorder) EventsThisMonth(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventsThisMonth", reflect.TypeOf((*MockUsageReader)(nil).EventsThisMonth), ctx, orgID)
}

// MockAdminStore is a mock of AdminStore interface.
type MockAdminStore struct {
	ctrl     *gomock.Controller
	recorder *MockAdminStoreMockRecorder
	isgomock struct{}
}

// MockAdminStoreMockRecorder is the mock recorder for MockAdminStore.
type MockAdminStoreMockRecorder struct {
	mock *MockAdminStore
}

// NewMockAdminStore creates a new mock instance.
func NewMockAdminStore(ctrl *gomock.Controller) *MockAdminStore {
	mock := &MockAdminStore{ctrl: ctrl}
	mock.recorder = &MockAdminStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminStore) EXPECT() *MockAdminStoreMockRecorder {
	return m.recorder
}

// ClicksPerDay mocks base method.
func (m *MockAdminStore) ClicksPerDay(ctx *gofr.Context, since string) ([]models.DayCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClicksPerDay", ctx, since)
	ret0, _ := ret[0].([]models.DayCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClicksPerDay indicates an expected call of ClicksPerDay.
func (mr *MockAdminStoreMockRecorder) ClicksPerDay(ctx, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClicksPerDay", reflect.TypeOf((*MockAdminStore)(nil).ClicksPerDay), ctx, since)
}

// CountOrgs mocks base method.
func (m *MockAdminStore) CountOrgs(ctx *gofr.Context, query string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOrgs", ctx, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOrgs indicates an expected call of CountOrgs.
func (mr *MockAdminStoreMockRecorder) CountOrgs(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOrgs", reflect.TypeOf((*MockAdminStore)(nil).CountOrgs), ctx, query)
}

// CountReports mocks base method.
func (m *MockAdminStore) CountReports(ctx *gofr.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountReports", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountReports indicates an expected call of CountReports.
func (mr *MockAdminStoreMockRecorder) CountReports(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountReports", reflect.TypeOf((*MockAdminStore)(nil).CountReports), ctx)
}

// CountUsers mocks base method.
func (m *MockAdminStore) CountUsers(ctx *gofr.Context, query string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", ctx, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockAdminStoreMockRecorder) CountUsers(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockAdminStore)(nil).CountUsers), ctx, query)
}

// GetLink mocks base method.
func (m *MockAdminStore) GetLink(ctx *gofr.Context, id int64) (*models.AdminLinkDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLink", ctx, id)
	ret0, _ := ret[0].(*models.AdminLinkDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLink indicates an expected call of GetLink.
func (mr *MockAdminStoreMockRecorder) GetLink(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLink", reflect.TypeOf((*MockAdminStore)(nil).GetLink), ctx, id)
}

// LinksCreatedPerDay mocks base method.
func (m *MockAdminStore) LinksCreatedPerDay(ctx *gofr.Context, since string) ([]models.DayCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinksCreatedPerDay", ctx, since)
	ret0, _ := ret[0].([]models.DayCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinksCreatedPerDay indicates an expected call of LinksCreatedPerDay.
func (mr *MockAdminStoreMockRecorder) LinksCreatedPerDay(ctx, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinksCreatedPerDay", reflect.TypeOf((*MockAdminStore)(nil).LinksCreatedPerDay), ctx, since)
}

// ListOrgs mocks base method.
func (m *MockAdminStore) ListOrgs(ctx *gofr.Context, query string, limit, offset int) ([]models.AdminOrg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrgs", ctx, query, limit, offset)
	ret0, _ := ret[0].([]models.AdminOrg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrgs indicates an expected call of ListOrgs.
func (mr *MockAdminStoreMockRecorder) ListOrgs(ctx, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrgs", reflect.TypeOf((*MockAdminStore)(nil).ListOrgs), ctx, query, limit, offset)
}

// ListReports mocks base method.
func (m *MockAdminStore) ListReports(ctx *gofr.Context, limit, offset int) ([]models.AdminReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReports", ctx, limit, offset)
	ret0, _ := ret[0].([]models.AdminReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReports indicates an expected call of ListReports.
func (mr *MockAdminStoreMockRecorder) ListReports(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReports", reflect.TypeOf((*MockAdminStore)(nil).ListReports), ctx, limit, offset)
}

// ListUsers mocks base method.
func (m *MockAdminStore) ListUsers(ctx *gofr.Context, query string, limit, offset int) ([]models.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, query, limit, offset)
	ret0, _ := ret[0].([]models.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockAdminStoreMockRecorder) ListUsers(ctx, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockAdminStore)(nil).ListUsers), ctx, query, limit, offset)
}

// OrgCounts mocks base method.
func (m *MockAdminStore) OrgCounts(ctx *gofr.Context, orgIDs []int64, clicksSince string) (map[int64]models.AdminOrgCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrgCounts", ctx, orgIDs, clicksSince)
	ret0, _ := ret[0].(map[int64]models.AdminOrgCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrgCounts indicates an expected call of OrgCounts.
func (mr *MockAdminStoreMockRecorder) OrgCounts(ctx, orgIDs, clicksSince any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrgCounts", reflect.TypeOf((*MockAdminStore)(nil).OrgCounts), ctx, orgIDs, clicksSince)
}

// SignupsPerDay mocks base method.
func (m *MockAdminStore) SignupsPerDay(ctx *gofr.Context, since string) ([]models.DayCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignupsPerDay", ctx, since)
	ret0, _ := ret[0].([]models.DayCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignupsPerDay indicates an expected call of SignupsPerDay.
func (mr *MockAdminStoreMockRecorder) SignupsPerDay(ctx, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignupsPerDay", reflect.TypeOf((*MockAdminStore)(nil).SignupsPerDay), ctx, since)
}

// UserOrgs mocks base method.
func (m *MockAdminStore) UserOrgs(ctx *gofr.Context, userIDs []int64) (map[int64][]models.AdminUserOrg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserOrgs", ctx, userIDs)
	ret0, _ := ret[0].(map[int64][]models.AdminUserOrg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserOrgs indicates an expected call of UserOrgs.
func (mr *MockAdminStoreMockRecorder) UserOrgs(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserOrgs", reflect.TypeOf((*MockAdminStore)(nil).UserOrgs), ctx, userIDs)
}

// MockLinkStatusStore is a mock of LinkStatusStore interface.
type MockLinkStatusStore struct {
	ctrl     *gomock.Controller
	recorder *MockLinkStatusStoreMockRecorder
	isgomock struct{}
}

// MockLinkStatusStoreMockRecorder is the mock recorder for MockLinkStatusStore.
type MockLinkStatusStoreMockRecorder struct {
	mock *MockLinkStatusStore
}

// NewMockLinkStatusStore creates a new mock instance.
func NewMockLinkStatusStore(ctrl *gomock.Controller) *MockLinkStatusStore {
	mock := &MockLinkStatusStore{ctrl: ctrl}
	mock.recorder = &MockLinkStatusStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkStatusStore) EXPECT() *MockLinkStatusStoreMockRecorder {
	return m.recorder
}

// SetStatusByID mocks base method.
func (m *MockLinkStatusStore) SetStatusByID(ctx *gofr.Context, id int64, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatusByID", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatusByID indicates an expected call of SetStatusByID.
func (mr *MockLinkStatusStoreMockRecorder) SetStatusByID(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatusByID", reflect.TypeOf((*MockLinkStatusStore)(nil).SetStatusByID), ctx, id, status)
}

// MockRuleStore is a mock of RuleStore interface.
type MockRuleStore struct {
	ctrl     *gomock.Controller
	recorder *MockRuleStoreMockRecorder
	isgomock struct{}
}

// MockRuleStoreMockRecorder is the mock recorder for MockRuleStore.
type MockRuleStoreMockRecorder struct {
	mock *MockRuleStore
}

// NewMockRuleStore creates a new mock instance.
func NewMockRuleStore(ctrl *gomock.Controller) *MockRuleStore {
	mock := &MockRuleStore{ctrl: ctrl}
	mock.recorder = &MockRuleStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleStore) EXPECT() *MockRuleStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRuleStore) Create(ctx *gofr.Context, r *models.Rule) (*models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(*models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRuleStoreMockRecorder) Create(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRuleStore)(nil).Create), ctx, r)
}

// Delete mocks base method.
func (m *MockRuleStore) Delete(ctx *gofr.Context, orgID, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, orgID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRuleStoreMockRecorder) Delete(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRuleStore)(nil).Delete), ctx, orgID, id)
}

// GetByID mocks base method.
func (m *MockRuleStore) GetByID(ctx *gofr.Context, orgID, id int64) (*models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, orgID, id)
	ret0, _ := ret[0].(*models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRuleStoreMockRecorder) GetByID(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRuleStore)(nil).GetByID), ctx, orgID, id)
}

// ListByLink mocks base method.
func (m *MockRuleStore) ListByLink(ctx *gofr.Context, orgID, linkID int64) ([]models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByLink", ctx, orgID, linkID)
	ret0, _ := ret[0].([]models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByLink indicates an expected call of ListByLink.
func (mr *MockRuleStoreMockRecorder) ListByLink(ctx, orgID, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByLink", reflect.TypeOf((*MockRuleStore)(nil).ListByLink), ctx, orgID, linkID)
}

// Update mocks base method.
func (m *MockRuleStore) Update(ctx *gofr.Context, r *models.Rule) (*models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, r)
	ret0, _ := ret[0].(*models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRuleStoreMockRecorder) Update(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRuleStore)(nil).Update), ctx, r)
}

// MockLocationResolver is a mock of LocationResolver interface.
type MockLocationResolver struct {
	ctrl     *gomock.Controller
	recorder *MockLocationResolverMockRecorder
	isgomock struct{}
}

// MockLocationResolverMockRecorder is the mock recorder for MockLocationResolver.
type MockLocationResolverMockRecorder struct {
	mock *MockLocationResolver
}

// NewMockLocationResolver creates a new mock instance.
func NewMockLocationResolver(ctrl *gomock.Controller) *MockLocationResolver {
	mock := &MockLocationResolver{ctrl: ctrl}
	mock.recorder = &MockLocationResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationResolver) EXPECT() *MockLocationResolverMockRecorder {
	return m.recorder
}

// LocationForIP mocks base method.
func (m *MockLocationResolver) LocationForIP(ip string) geo.Location {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LocationForIP", ip)
	ret0, _ := ret[0].(geo.Location)
	return ret0
}

// LocationForIP indicates an expected call of LocationForIP.
func (mr *MockLocationResolverMockRecorder) LocationForIP(ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LocationForIP", reflect.TypeOf((*MockLocationResolver)(nil).LocationForIP), ip)
}
