// Code generated by MockGen. DO NOT EDIT.
// Source: handlers/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=handlers/interfaces.go -destination=handlers/mock_interfaces.go -package=handlers
//

// Package handlers is a generated GoMock package.
package handlers

import (
	reflect "reflect"

	auth "github.com/opengittr/ogtr/backend/auth"
	models "github.com/opengittr/ogtr/backend/models"
	services "github.com/opengittr/ogtr/backend/services"
	visitor "github.com/opengittr/ogtr/backend/visitor"
	gomock "go.uber.org/mock/gomock"
	gofr "gofr.dev/pkg/gofr"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthService) Login(ctx *gofr.Context, provider, credential string) (*services.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, provider, credential)
	ret0, _ := ret[0].(*services.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceMockRecorder) Login(ctx, provider, credential any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), ctx, provider, credential)
}

// Me mocks base method.
func (m *MockAuthService) Me(ctx *gofr.Context, claims *auth.SessionClaims) (*services.MeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Me", ctx, claims)
	ret0, _ := ret[0].(*services.MeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Me indicates an expected call of Me.
func (mr *MockAuthServiceMockRecorder) Me(ctx, claims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Me", reflect.TypeOf((*MockAuthService)(nil).Me), ctx, claims)
}

// Refresh mocks base method.
func (m *MockAuthService) Refresh(ctx *gofr.Context, refreshToken string) (models.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, refreshToken)
	ret0, _ := ret[0].(models.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockAuthServiceMockRecorder) Refresh(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockAuthService)(nil).Refresh), ctx, refreshToken)
}

// SwitchOrg mocks base method.
func (m *MockAuthService) SwitchOrg(ctx *gofr.Context, userID, orgID int64) (models.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchOrg", ctx, userID, orgID)
	ret0, _ := ret[0].(models.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SwitchOrg indicates an expected call of SwitchOrg.
func (mr *MockAuthServiceMockRecorder) SwitchOrg(ctx, userID, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchOrg", reflect.TypeOf((*MockAuthService)(nil).SwitchOrg), ctx, userID, orgID)
}

// MockLinkService is a mock of LinkService interface.
type MockLinkService struct {
	ctrl     *gomock.Controller
	recorder *MockLinkServiceMockRecorder
	isgomock struct{}
}

// MockLinkServiceMockRecorder is the mock recorder for MockLinkService.
type MockLinkServiceMockRecorder struct {
	mock *MockLinkService
}

// NewMockLinkService creates a new mock instance.
func NewMockLinkService(ctrl *gomock.Controller) *MockLinkService {
	mock := &MockLinkService{ctrl: ctrl}
	mock.recorder = &MockLinkServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkService) EXPECT() *MockLinkServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockLinkService) Get(ctx *gofr.Context, orgID, viewerID, id int64) (*models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, orgID, viewerID, id)
	ret0, _ := ret[0].(*models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLinkServiceMockRecorder) Get(ctx, orgID, viewerID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLinkService)(nil).Get), ctx, orgID, viewerID, id)
}

// List mocks base method.
func (m *MockLinkService) List(ctx *gofr.Context, orgID, viewerID int64, page int) (*services.LinkPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, orgID, viewerID, page)
	ret0, _ := ret[0].(*services.LinkPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockLinkServiceMockRecorder) List(ctx, orgID, viewerID, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLinkService)(nil).List), ctx, orgID, viewerID, page)
}

// QRCodePNG mocks base method.
func (m *MockLinkService) QRCodePNG(ctx *gofr.Context, orgID, viewerID, id int64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QRCodePNG", ctx, orgID, viewerID, id)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QRCodePNG indicates an expected call of QRCodePNG.
func (mr *MockLinkServiceMockRecorder) QRCodePNG(ctx, orgID, viewerID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QRCodePNG", reflect.TypeOf((*MockLinkService)(nil).QRCodePNG), ctx, orgID, viewerID, id)
}

// SetAlias mocks base method.
func (m *MockLinkService) SetAlias(ctx *gofr.Context, orgID, viewerID, id int64, alias string) (*models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAlias", ctx, orgID, viewerID, id, alias)
	ret0, _ := ret[0].(*models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetAlias indicates an expected call of SetAlias.
func (mr *MockLinkServiceMockRecorder) SetAlias(ctx, orgID, viewerID, id, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAlias", reflect.TypeOf((*MockLinkService)(nil).SetAlias), ctx, orgID, viewerID, id, alias)
}

// SetDeeplink mocks base method.
func (m *MockLinkService) SetDeeplink(ctx *gofr.Context, orgID, viewerID, id int64, cfg *models.DeeplinkConfig) (*models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDeeplink", ctx, orgID, viewerID, id, cfg)
	ret0, _ := ret[0].(*models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetDeeplink indicates an expected call of SetDeeplink.
func (mr *MockLinkServiceMockRecorder) SetDeeplink(ctx, orgID, viewerID, id, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDeeplink", reflect.TypeOf((*MockLinkService)(nil).SetDeeplink), ctx, orgID, viewerID, id, cfg)
}

// Shorten mocks base method.
func (m *MockLinkService) Shorten(ctx *gofr.Context, orgID, userID int64, in services.ShortenInput) (*models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shorten", ctx, orgID, userID, in)
	ret0, _ := ret[0].(*models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Shorten indicates an expected call of Shorten.
func (mr *MockLinkServiceMockRecorder) Shorten(ctx, orgID, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shorten", reflect.TypeOf((*MockLinkService)(nil).Shorten), ctx, orgID, userID, in)
}

// ShortenViaAPIKey mocks base method.
func (m *MockLinkService) ShortenViaAPIKey(ctx *gofr.Context, orgID, apiKeyID int64, in services.ShortenInput) (*models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortenViaAPIKey", ctx, orgID, apiKeyID, in)
	ret0, _ := ret[0].(*models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShortenViaAPIKey indicates an expected call of ShortenViaAPIKey.
func (mr *MockLinkServiceMockRecorder) ShortenViaAPIKey(ctx, orgID, apiKeyID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortenViaAPIKey", reflect.TypeOf((*MockLinkService)(nil).ShortenViaAPIKey), ctx, orgID, apiKeyID, in)
}

// UpdateDestination mocks base method.
func (m *MockLinkService) UpdateDestination(ctx *gofr.Context, orgID, actorID, id int64, in services.EditInput) (*models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDestination", ctx, orgID, actorID, id, in)
	ret0, _ := ret[0].(*models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDestination indicates an expected call of UpdateDestination.
func (mr *MockLinkServiceMockRecorder) UpdateDestination(ctx, orgID, actorID, id, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDestination", reflect.TypeOf((*MockLinkService)(nil).UpdateDestination), ctx, orgID, actorID, id, in)
}

// MockAPIKeyService is a mock of APIKeyService interface.
type MockAPIKeyService struct {
	ctrl     *gomock.Controller
	recorder *MockAPIKeyServiceMockRecorder
	isgomock struct{}
}

// MockAPIKeyServiceMockRecorder is the mock recorder for MockAPIKeyService.
type MockAPIKeyServiceMockRecorder struct {
	mock *MockAPIKeyService
}

// NewMockAPIKeyService creates a new mock instance.
func NewMockAPIKeyService(ctrl *gomock.Controller) *MockAPIKeyService {
	mock := &MockAPIKeyService{ctrl: ctrl}
	mock.recorder = &MockAPIKeyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIKeyService) EXPECT() *MockAPIKeyServiceMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockAPIKeyService) Authenticate(ctx *gofr.Context, rawKey string) (*models.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, rawKey)
	ret0, _ := ret[0].(*models.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockAPIKeyServiceMockRecorder) Authenticate(ctx, rawKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockAPIKeyService)(nil).Authenticate), ctx, rawKey)
}

// Create mocks base method.
func (m *MockAPIKeyService) Create(ctx *gofr.Context, orgID int64, name string) (*services.CreatedAPIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, orgID, name)
	ret0, _ := ret[0].(*services.CreatedAPIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAPIKeyServiceMockRecorder) Create(ctx, orgID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAPIKeyService)(nil).Create), ctx, orgID, name)
}

// Disable mocks base method.
func (m *MockAPIKeyService) Disable(ctx *gofr.Context, orgID, id int64) (*models.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable", ctx, orgID, id)
	ret0, _ := ret[0].(*models.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Disable indicates an expected call of Disable.
func (mr *MockAPIKeyServiceMockRecorder) Disable(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockAPIKeyService)(nil).Disable), ctx, orgID, id)
}

// List mocks base method.
func (m *MockAPIKeyService) List(ctx *gofr.Context, orgID int64) ([]models.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, orgID)
	ret0, _ := ret[0].([]models.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAPIKeyServiceMockRecorder) List(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAPIKeyService)(nil).List), ctx, orgID)
}

// MockRuleService is a mock of RuleService interface.
type MockRuleService struct {
	ctrl     *gomock.Controller
	recorder *MockRuleServiceMockRecorder
	isgomock struct{}
}

// MockRuleServiceMockRecorder is the mock recorder for MockRuleService.
type MockRuleServiceMockRecorder struct {
	mock *MockRuleService
}

// NewMockRuleService creates a new mock instance.
func NewMockRuleService(ctrl *gomock.Controller) *MockRuleService {
	mock := &MockRuleService{ctrl: ctrl}
	mock.recorder = &MockRuleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleService) EXPECT() *MockRuleServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRuleService) Create(ctx *gofr.Context, orgID, viewerID, linkID int64, inputs []services.RuleInput) ([]models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, orgID, viewerID, linkID, inputs)
	ret0, _ := ret[0].([]models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRuleServiceMockRecorder) Create(ctx, orgID, viewerID, linkID, inputs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRuleService)(nil).Create), ctx, orgID, viewerID, linkID, inputs)
}

// Delete mocks base method.
func (m *MockRuleService) Delete(ctx *gofr.Context, orgID, viewerID, ruleID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, orgID, viewerID, ruleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRuleServiceMockRecorder) Delete(ctx, orgID, viewerID, ruleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRuleService)(nil).Delete), ctx, orgID, viewerID, ruleID)
}

// List mocks base method.
func (m *MockRuleService) List(ctx *gofr.Context, orgID, viewerID, linkID int64) ([]models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, orgID, viewerID, linkID)
	ret0, _ := ret[0].([]models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRuleServiceMockRecorder) List(ctx, orgID, viewerID, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRuleService)(nil).List), ctx, orgID, viewerID, linkID)
}

// Update mocks base method.
func (m *MockRuleService) Update(ctx *gofr.Context, orgID, viewerID, ruleID int64, in services.RuleInput) (*models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, orgID, viewerID, ruleID, in)
	ret0, _ := ret[0].(*models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRuleServiceMockRecorder) Update(ctx, orgID, viewerID, ruleID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRuleService)(nil).Update), ctx, orgID, viewerID, ruleID, in)
}

// MockCityIndex is a mock of CityIndex interface.
type MockCityIndex struct {
	ctrl     *gomock.Controller
	recorder *MockCityIndexMockRecorder
	isgomock struct{}
}

// MockCityIndexMockRecorder is the mock recorder for MockCityIndex.
type MockCityIndexMockRecorder struct {
	mock *MockCityIndex
}

// NewMockCityIndex creates a new mock instance.
func NewMockCityIndex(ctrl *gomock.Controller) *MockCityIndex {
	mock := &MockCityIndex{ctrl: ctrl}
	mock.recorder = &MockCityIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCityIndex) EXPECT() *MockCityIndexMockRecorder {
	return m.recorder
}

// Enabled mocks base method.
func (m *MockCityIndex) Enabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled.
func (mr *MockCityIndexMockRecorder) Enabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*MockCityIndex)(nil).Enabled))
}

// Search mocks base method.
func (m *MockCityIndex) Search(prefix string, limit int) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", prefix, limit)
	ret0, _ := ret[0].([]string)
	return ret0
}

// Search indicates an expected call of Search.
func (mr *MockCityIndexMockRecorder) Search(prefix, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockCityIndex)(nil).Search), prefix, limit)
}

// MockResolveService is a mock of ResolveService interface.
type MockResolveService struct {
	ctrl     *gomock.Controller
	recorder *MockResolveServiceMockRecorder
	isgomock struct{}
}

// MockResolveServiceMockRecorder is the mock recorder for MockResolveService.
type MockResolveServiceMockRecorder struct {
	mock *MockResolveService
}

// NewMockResolveService creates a new mock instance.
func NewMockResolveService(ctrl *gomock.Controller) *MockResolveService {
	mock := &MockResolveService{ctrl: ctrl}
	mock.recorder = &MockResolveServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResolveService) EXPECT() *MockResolveServiceMockRecorder {
	return m.recorder
}

// PreviewByCode mocks base method.
func (m *MockResolveService) PreviewByCode(ctx *gofr.Context, code string, env visitor.Env) (*services.Preview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreviewByCode", ctx, code, env)
	ret0, _ := ret[0].(*services.Preview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreviewByCode indicates an expected call of PreviewByCode.
func (mr *MockResolveServiceMockRecorder) PreviewByCode(ctx, code, env any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreviewByCode", reflect.TypeOf((*MockResolveService)(nil).PreviewByCode), ctx, code, env)
}

// Resolve mocks base method.
func (m *MockResolveService) Resolve(ctx *gofr.Context, code, tag string, env visitor.Env) (*services.Resolution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, code, tag, env)
	ret0, _ := ret[0].(*services.Resolution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockResolveServiceMockRecorder) Resolve(ctx, code, tag, env any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockResolveService)(nil).Resolve), ctx, code, tag, env)
}

// MockReportService is a mock of ReportService interface.
type MockReportService struct {
	ctrl     *gomock.Controller
	recorder *MockReportServiceMockRecorder
	isgomock struct{}
}

// MockReportServiceMockRecorder is the mock recorder for MockReportService.
type MockReportServiceMockRecorder struct {
	mock *MockReportService
}

// NewMockReportService creates a new mock instance.
func NewMockReportService(ctrl *gomock.Controller) *MockReportService {
	mock := &MockReportService{ctrl: ctrl}
	mock.recorder = &MockReportServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportService) EXPECT() *MockReportServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReportService) Create(ctx *gofr.Context, in services.ReportInput, reporterIP string) (*models.AbuseReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in, reporterIP)
	ret0, _ := ret[0].(*models.AbuseReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockReportServiceMockRecorder) Create(ctx, in, reporterIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReportService)(nil).Create), ctx, in, reporterIP)
}

// MockStatsService is a mock of StatsService interface.
type MockStatsService struct {
	ctrl     *gomock.Controller
	recorder *MockStatsServiceMockRecorder
	isgomock struct{}
}

// MockStatsServiceMockRecorder is the mock recorder for MockStatsService.
type MockStatsServiceMockRecorder struct {
	mock *MockStatsService
}

// NewMockStatsService creates a new mock instance.
func NewMockStatsService(ctrl *gomock.Controller) *MockStatsService {
	mock := &MockStatsService{ctrl: ctrl}
	mock.recorder = &MockStatsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsService) EXPECT() *MockStatsServiceMockRecorder {
	return m.recorder
}

// LinkReport mocks base method.
func (m *MockStatsService) LinkReport(ctx *gofr.Context, orgID, viewerID, linkID int64, from, to string, deeplink bool) (*models.LinkStatsReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkReport", ctx, orgID, viewerID, linkID, from, to, deeplink)
	ret0, _ := ret[0].(*models.LinkStatsReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkReport indicates an expected call of LinkReport.
func (mr *MockStatsServiceMockRecorder) LinkReport(ctx, orgID, viewerID, linkID, from, to, deeplink any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkReport", reflect.TypeOf((*MockStatsService)(nil).LinkReport), ctx, orgID, viewerID, linkID, from, to, deeplink)
}

// Tags mocks base method.
func (m *MockStatsService) Tags(ctx *gofr.Context, orgID int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tags", ctx, orgID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tags indicates an expected call of Tags.
func (mr *MockStatsServiceMockRecorder) Tags(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tags", reflect.TypeOf((*MockStatsService)(nil).Tags), ctx, orgID)
}

// UTMAnalysis mocks base method.
func (m *MockStatsService) UTMAnalysis(ctx *gofr.Context, orgID, viewerID int64) (*models.UTMAnalysis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UTMAnalysis", ctx, orgID, viewerID)
	ret0, _ := ret[0].(*models.UTMAnalysis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UTMAnalysis indicates an expected call of UTMAnalysis.
func (mr *MockStatsServiceMockRecorder) UTMAnalysis(ctx, orgID, viewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UTMAnalysis", reflect.TypeOf((*MockStatsService)(nil).UTMAnalysis), ctx, orgID, viewerID)
}

// UniqueClicks mocks base method.
func (m *MockStatsService) UniqueClicks(ctx *gofr.Context, orgID int64, linkIDs []int64) (*models.UniqueClicksResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UniqueClicks", ctx, orgID, linkIDs)
	ret0, _ := ret[0].(*models.UniqueClicksResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UniqueClicks indicates an expected call of UniqueClicks.
func (mr *MockStatsServiceMockRecorder) UniqueClicks(ctx, orgID, linkIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UniqueClicks", reflect.TypeOf((*MockStatsService)(nil).UniqueClicks), ctx, orgID, linkIDs)
}

// MockDomainService is a mock of DomainService interface.
type MockDomainService struct {
	ctrl     *gomock.Controller
	recorder *MockDomainServiceMockRecorder
	isgomock struct{}
}

// MockDomainServiceMockRecorder is the mock recorder for MockDomainService.
type MockDomainServiceMockRecorder struct {
	mock *MockDomainService
}

// NewMockDomainService creates a new mock instance.
func NewMockDomainService(ctrl *gomock.Controller) *MockDomainService {
	mock := &MockDomainService{ctrl: ctrl}
	mock.recorder = &MockDomainServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomainService) EXPECT() *MockDomainServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDomainService) Create(ctx *gofr.Context, orgID, actorID int64, hostname string) (*models.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, orgID, actorID, hostname)
	ret0, _ := ret[0].(*models.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDomainServiceMockRecorder) Create(ctx, orgID, actorID, hostname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDomainService)(nil).Create), ctx, orgID, actorID, hostname)
}

// Delete mocks base method.
func (m *MockDomainService) Delete(ctx *gofr.Context, orgID, actorID, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, orgID, actorID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDomainServiceMockRecorder) Delete(ctx, orgID, actorID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDomainService)(nil).Delete), ctx, orgID, actorID, id)
}

// List mocks base method.
func (m *MockDomainService) List(ctx *gofr.Context, orgID int64) ([]models.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, orgID)
	ret0, _ := ret[0].([]models.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDomainServiceMockRecorder) List(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDomainService)(nil).List), ctx, orgID)
}

// SetPrimary mocks base method.
func (m *MockDomainService) SetPrimary(ctx *gofr.Context, orgID, actorID, id int64) (*models.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPrimary", ctx, orgID, actorID, id)
	ret0, _ := ret[0].(*models.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetPrimary indicates an expected call of SetPrimary.
func (mr *MockDomainServiceMockRecorder) SetPrimary(ctx, orgID, actorID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrimary", reflect.TypeOf((*MockDomainService)(nil).SetPrimary), ctx, orgID, actorID, id)
}

// Verify mocks base method.
func (m *MockDomainService) Verify(ctx *gofr.Context, orgID, actorID, id int64) (*models.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, orgID, actorID, id)
	ret0, _ := ret[0].(*models.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockDomainServiceMockRecorder) Verify(ctx, orgID, actorID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockDomainService)(nil).Verify), ctx, orgID, actorID, id)
}

// MockOrgService is a mock of OrgService interface.
type MockOrgService struct {
	ctrl     *gomock.Controller
	recorder *MockOrgServiceMockRecorder
	isgomock struct{}
}

// MockOrgServiceMockRecorder is the mock recorder for MockOrgService.
type MockOrgServiceMockRecorder struct {
	mock *MockOrgService
}

// NewMockOrgService creates a new mock instance.
func NewMockOrgService(ctrl *gomock.Controller) *MockOrgService {
	mock := &MockOrgService{ctrl: ctrl}
	mock.recorder = &MockOrgServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrgService) EXPECT() *MockOrgServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrgService) Create(ctx *gofr.Context, creatorID int64, name, autoJoinDomain string) (*models.Org, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, creatorID, name, autoJoinDomain)
	ret0, _ := ret[0].(*models.Org)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrgServiceMockRecorder) Create(ctx, creatorID, name, autoJoinDomain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrgService)(nil).Create), ctx, creatorID, name, autoJoinDomain)
}

// CreateInvite mocks base method.
func (m *MockOrgService) CreateInvite(ctx *gofr.Context, orgID, actorID int64, email string) (*models.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvite", ctx, orgID, actorID, email)
	ret0, _ := ret[0].(*models.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvite indicates an expected call of CreateInvite.
func (mr *MockOrgServiceMockRecorder) CreateInvite(ctx, orgID, actorID, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvite", reflect.TypeOf((*MockOrgService)(nil).CreateInvite), ctx, orgID, actorID, email)
}

// Get mocks base method.
func (m *MockOrgService) Get(ctx *gofr.Context, orgID int64) (*models.Org, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, orgID)
	ret0, _ := ret[0].(*models.Org)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOrgServiceMockRecorder) Get(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrgService)(nil).Get), ctx, orgID)
}

// ListInvites mocks base method.
func (m *MockOrgService) ListInvites(ctx *gofr.Context, orgID int64) ([]models.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvites", ctx, orgID)
	ret0, _ := ret[0].([]models.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvites indicates an expected call of ListInvites.
func (mr *MockOrgServiceMockRecorder) ListInvites(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvites", reflect.TypeOf((*MockOrgService)(nil).ListInvites), ctx, orgID)
}

// Members mocks base method.
func (m *MockOrgService) Members(ctx *gofr.Context, orgID int64) ([]models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Members", ctx, orgID)
	ret0, _ := ret[0].([]models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Members indicates an expected call of Members.
func (mr *MockOrgServiceMockRecorder) Members(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Members", reflect.TypeOf((*MockOrgService)(nil).Members), ctx, orgID)
}

// RemoveMember mocks base method.
func (m *MockOrgService) RemoveMember(ctx *gofr.Context, orgID, actorID, targetID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, orgID, actorID, targetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockOrgServiceMockRecorder) RemoveMember(ctx, orgID, actorID, targetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockOrgService)(nil).RemoveMember), ctx, orgID, actorID, targetID)
}

// RevokeInvite mocks base method.
func (m *MockOrgService) RevokeInvite(ctx *gofr.Context, orgID, actorID, inviteID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeInvite", ctx, orgID, actorID, inviteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeInvite indicates an expected call of RevokeInvite.
func (mr *MockOrgServiceMockRecorder) RevokeInvite(ctx, orgID, actorID, inviteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeInvite", reflect.TypeOf((*MockOrgService)(nil).RevokeInvite), ctx, orgID, actorID, inviteID)
}

// Update mocks base method.
func (m *MockOrgService) Update(ctx *gofr.Context, orgID, actorID int64, patch services.OrgUpdate) (*models.Org, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, orgID, actorID, patch)
	ret0, _ := ret[0].(*models.Org)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockOrgServiceMockRecorder) Update(ctx, orgID, actorID, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrgService)(nil).Update), ctx, orgID, actorID, patch)
}
